variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

.docker-image:
  tags:
    - docker-builder
  image: docker:stable
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - lint
  - build

lint:python:
  stage: lint
  image: python:3.9-slim
  before_script:
    - pip install black
  script:
    - black --check --diff .

build:mcp-croit-ceph:
  stage: build
  extends:
    - .docker-image
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  after_script:
    - docker rmi -f $DOCKER_IMAGE
